dbt_demo:
  outputs:
    dev:
      dataset: dev
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('DBTDEMO_BQ_SA_KEY') }}"
      location: northamerica-northeast1
      method: service-account
      priority: interactive
      project: dbt-demo-474219
      threads: 1
      type: bigquery
    prod:
      dataset: prod
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('DBTDEMO_BQ_SA_KEY') }}"
      location: northamerica-northeast1
      method: service-account
      priority: interactive
      project: dbt-demo-474219
      threads: 1
      type: bigquery
  target: dev